config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  root to: 'home#index'

  namespace :home do
    get 'lista'
  end

  namespace :usuarios do
    get 'asignaciones_seguimiento'
    post 'actualizar_clave'
    post 'agregar_seguimiento'
    post 'quitar_seguimiento'
  end

  namespace :matrimonios do
    get 'lista'
    post 'destroy'
  end

  namespace :actividades do
    get 'matrimonios'
    post 'agregar_quitar_participante'
  end

  namespace :personas do
    get 'lista'
    post 'destroy'
    post 'guardar_seguimiento'
    get 'obtener_nota'
  end

  resources :usuarios
  resources :parametros
  resources :matrimonios
  resources :actividades
  resources :circulo_amistades
  resources :personas do
    resources :personas_nota_seguimiento, except: [:index, :show]
  end
end

app/models/parametro.rb
# encoding: utf-8

class Parametro < ApplicationRecord

  audited
  strip_attributes

  # ------------------------------------------------------------------------------------------------
  # Validaciones
  # ------------------------------------------------------------------------------------------------

  validates :codigo, presence: true,
                     uniqueness: true,
                     length: { maximum: 10 }

  validates :nombre, presence: true,
                     uniqueness: true,
                     length: { maximum: 1000 }

  validates :valor, presence: true,
                    uniqueness: true,
                    length: { maximum: 1000 }

end

app/controllers/parametros_controller.rb
class ParametrosController < ApplicationController
  before_action :set_parametro, only: [:show, :edit, :update, :destroy]
  check_authorization
  load_and_authorize_resource

  # GET /parametros
  # GET /parametros.json
  def index
    @parametros = Parametro.all
  end

  # GET /parametros/1
  # GET /parametros/1.json
  def show
  end

  # GET /parametros/new
  def new
    @parametro = Parametro.new
  end

  # GET /parametros/1/edit
  def edit
  end

  # POST /parametros
  # POST /parametros.json
  def create
    @parametro = Parametro.new(parametro_params)

    respond_to do |format|
      if @parametro.save
        format.html { redirect_to @parametro, notice: 'Creado correctamente' }
        format.json { render :show, status: :created, location: @parametro }
      else
        format.html { render :new }
        format.json { render json: @parametro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parametros/1
  # PATCH/PUT /parametros/1.json
  def update
    respond_to do |format|
      if @parametro.update(parametro_params)
        format.html { redirect_to @parametro, notice: 'Actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @parametro }
      else
        format.html { render :edit }
        format.json { render json: @parametro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parametros/1
  # DELETE /parametros/1.json
  def destroy
    @parametro.destroy
    respond_to do |format|
      format.html { redirect_to parametros_url, notice: 'Eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parametro
      @parametro = Parametro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parametro_params
      params.require(:parametro).permit(:codigo, :nombre, :valor)
    end
end

app/helpers/parametros_helper.rb
module ParametrosHelper
end

app/views/parametros/_form.html.erb
<div class="box box-primary">
  <%= form_with(model: parametro, local: true, class: 'form-horizontal') do |form| %>

    <div class="box-header with-border">
      <div class="row">
        <div class="col-xs-12 col-md-9">
        </div>
        <div class="col-xs-4 col-md-1">
          <%= link_to 'Regresar', parametros_path, class: 'btn btn-default btn-block' %>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= submit_tag 'Guardar', class: "btn btn-primary btn-block" %>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= link_to 'Nuevo', new_parametro_path, { class: 'btn btn-primary btn-block'} %>
        </div>
      </div>
    </div>

  <div class="box-body">
    <div class="form-group">
      <%= form.label :codigo, 'Código', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.text_field :codigo, id: :parametro_codigo, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :nombre, 'Nombre', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.text_field :nombre, id: :parametro_nombre, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :valor, 'Valor', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.text_field :valor, id: :parametro_valor, class: 'form-control' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/parametros/edit.html.erb
<section class="content-header">
  <h1>
    Parámetro
    <small>Editar #<%=@parametro.id%></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="/parametros"><i class="fa fa-book"></i> Parámetros</a></li>
    <li class="active">Editar</li>
  </ol>
</section>
<section class="content">
  <%= render 'form', parametro: @parametro %>
</section>

app/views/parametros/index.html.erb
<section class="content-header">
  <h1>Parámetros</h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active"><i class="fa fa-book"></i> Parámetros</li>
  </ol>
</section>

<section class="content">
  <div class="box box-primary">
    <div class="box-header">
        <div class="row">
          <div class="col-xs-12 col-md-10">
          </div>
          <div class="col-xs-12 col-md-2">
            <% if can? :create, Parametro %>
            <%= link_to 'Nuevo', new_parametro_path, { class: 'btn btn-primary btn-block'} %>
            <% end -%>
          </div>
        </div>
    </div>
    <div class="box-body">

    <div class="row">
      <div class="col-xs-1"><strong>Código</strong></div>
      <div class="col-xs-8"><strong>Nombre</strong></div>
      <div class="col-xs-1"><strong>Valor</strong></div>
      <div class="col-xs-1"></div>
      <div class="col-xs-1"></div>
    </div>

    <% @parametros.each do |parametro| %>
    <div class="row">
      <div class="col-xs-1"><%= parametro.codigo %></div>
      <div class="col-xs-8"><%= parametro.nombre %></div>
      <div class="col-xs-1"><%= parametro.valor %></div>
      <div class="col-xs-1">
        <% if can? :create, parametro %>
        <%= link_to 'Editar', edit_parametro_path(parametro), class: "btn btn-xs btn-primary btn-block" %>
        <% end -%>
      </div>
      <div class="col-xs-1">
        <% if can? :destroy, parametro %>
        <%= link_to 'Eliminar', parametro, method: :delete, data: { confirm: 'Seguro de eliminar?' },class: "btn btn-xs btn-danger btn-block" %>
        <% end -%>
        </div>
    </div>
    <% end %>

    </div>
  </div>
</section>

app/views/parametros/new.html.erb
<section class="content-header">
  <h1>
    Parámetro
    <small>Nuevo</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="/parametros"><i class="fa fa-book"></i> Parámetros</a></li>
    <li class="active">nuevo</li>
  </ol>
</section>
<section class="content">
  <%= render 'form', parametro: @parametro %>
</section>

app/views/parametros/show.html.erb
<%= render 'shared/page_title', title: 'Parámetro',
                                small_title: "ID ##{@parametro.id}",
                                navigation: [{ title: 'Parámetros', url: '/parametros', icon: 'fa-cogs' },
                                             { title: 'Ver', url: '#', icon: 'fa-circle-o' }] %>
 <section class="content">

  <div class="box box-primary">
    <div class="box-header with-border">
      <div class="row">
        <div class="col-xs-12 col-md-11">
        </div>
        <div class="col-xs-12 col-md-1">
          <%= link_to 'Regresar', parametros_path, class: 'btn btn-default btn-block' %>
        </div>
      </div>
    </div>

    <div class="box-body">
      <div class="row">
        <div class="col-xs-2">
          <strong>Código:</strong>
        </div>
        <div class="col-xs-10">
          <%= @parametro.codigo %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-2">
          <strong>Nombre:</strong>
        </div>
        <div class="col-xs-10">
          <%= @parametro.nombre %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-2">
          <strong>Valor:</strong>
        </div>
        <div class="col-xs-10">
          <%= @parametro.valor %>
        </div>
      </div>

    </div>
  </div>

</section>