config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  root to: 'home#index'

  namespace :home do
    get 'lista'
  end

  namespace :usuarios do
    get 'asignaciones_seguimiento'
    post 'actualizar_clave'
    post 'agregar_seguimiento'
    post 'quitar_seguimiento'
  end

  namespace :matrimonios do
    get 'lista'
    post 'destroy'
  end

  namespace :actividades do
    get 'matrimonios'
    post 'agregar_quitar_participante'
  end

  namespace :personas do
    get 'lista'
    post 'destroy'
    post 'guardar_seguimiento'
    get 'obtener_nota'
  end

  resources :usuarios
  resources :parametros
  resources :matrimonios
  resources :actividades
  resources :circulo_amistades
  resources :personas do
    resources :personas_nota_seguimiento, except: [:index, :show]
  end
end

app/models/matrimonio.rb
# encoding: utf-8

class Matrimonio < ApplicationRecord

  include PgSearch
  include UpcaseAttributes

  audited
  strip_attributes

  # ------------------------------------------------------------------------------------------------
  # Validaciones
  # ------------------------------------------------------------------------------------------------

  validates :esposo_id, uniqueness: true, presence: true

  validates :esposa_id, uniqueness: true, presence: true

  # ------------------------------------------------------------------------------------------------
  # Relaciones
  # ------------------------------------------------------------------------------------------------

  belongs_to :esposo,
             class_name: 'Persona',
             foreign_key: 'esposo_id'

  belongs_to :esposa,
             class_name: 'Persona',
             foreign_key: 'esposa_id'

  has_many :actividades,
           class_name: 'IntegranteActividad',
           foreign_key: 'matrimonio_id'

  # ------------------------------------------------------------------------------------------------
  # Callbacks
  # ------------------------------------------------------------------------------------------------
  before_destroy :relaciones?
  before_save :validar_boda_eclesiastica

  # ------------------------------------------------------------------------------------------------
  # Métodos
  # ------------------------------------------------------------------------------------------------

  def relaciones?
    errors.add(:base, 'Tiene participación en actividades') if actividades.any?
    throw :abort if errors.any?
  end

  pg_search_scope(:buscar,
                  associated_against: { esposo: [:primer_nombre,
                                                 :segundo_nombre,
                                                 :primer_apellido,
                                                 :segundo_apellido],
                                        esposa: [:primer_nombre,
                                                 :segundo_nombre,
                                                 :primer_apellido,
                                                 :segundo_apellido] },
                  using: {
                    tsearch: {
                      dictionary: 'spanish',
                      normalization: 2
                    }
                  })

  def self.todos
    count
  end

  def self.sin_matrimonio
    where(boda_civil: false).count
  end

  def self.solo_boda_civil
    where(boda_civil: true, boda_eclesiastica: false).count
  end

  def self.boda_civl_y_eclesiastica
    where(boda_civil: true, boda_eclesiastica: true).count
  end

  def tiene_actividades?
    actividades.any?
  end

  def participa_en_actividad?(actividad)
    actividades.where(actividad_id: actividad.id).exists?
  end

  def nombre
    esposo.primer_apellido + ' ' + esposa.primer_apellido
  end

  def situacion
    boda_eclesiastica || boda_civil ? 'MATRIMONIO' : 'PAREJA'
  end

  def situacion_nombre
    situacion + ' ' + nombre
  end

  def estado_civil
    if boda_eclesiastica
      2
    elsif boda_civil
      1
    else
      0
    end
  end

  def validar_boda_eclesiastica
    if boda_eclesiastica && !boda_civil
      errors.add(:base, 'No está permitido registrar boda eclesiástica si no ha marcado boda civil')
      throw :abort
    else
      return true
    end
  end

end

app/controllers/matrimonios_controller.rb
# encoding: utf-8

class MatrimoniosController < ApplicationController
  before_action :set_matrimonio, only: [:show, :edit, :update, :destroy]
  check_authorization
  load_and_authorize_resource

  # GET /matrimonios
  # GET /matrimonios.json
  def index
    @buscar = params[:buscar]
  end

  def lista
    @matrimonios = []
    @matrimonios = Matrimonio.buscar(params[:buscar]) unless params[:buscar].blank?
    render 'matrimonios', layout: false
  end

  # GET /matrimonios/1
  # GET /matrimonios/1.json
  def show
    @actividades = Actividad.joins(:integrantes)
                            .where(integrante_actividades: { matrimonio_id: @matrimonio.id })
                            .order(fecha: :desc)
  end

  # GET /matrimonios/new
  def new
    @matrimonio = Matrimonio.new
  end

  # GET /matrimonios/1/edit
  def edit
  end

  # POST /matrimonios
  # POST /matrimonios.json
  def create
    begin
      ActiveRecord::Base.transaction do
        @el = Persona.new(el_params)
        @ella = Persona.new(ella_params)

        raise Util::Mensaje.mensajes_error_modelo(@el.errors) unless @el.save
        raise Util::Mensaje.mensajes_error_modelo(@ella.errors) unless @ella.save

        @matrimonio = Matrimonio.new(matrimonio_params)
        @matrimonio.esposo_id = @el.id
        @matrimonio.esposa_id = @ella.id
        unless @matrimonio.save
          raise Util::Mensaje.mensajes_error_modelo(@matrimonio.errors)
        end

        flash[:notice] = 'Registrado correctamente'
        redirect_to '/matrimonios/' + @matrimonio.id.to_s + '/edit'
      end
    rescue StandardError => e
      flash[:alert] = 'Error al registrar: ' + Util::Mensaje.limpiar_mensaje(e.message)
      render 'new'
    end
  end

  # PATCH/PUT /matrimonios/1
  # PATCH/PUT /matrimonios/1.json
  def update
    begin
      ActiveRecord::Base.transaction do
        @matrimonio = Matrimonio.find(params[:id])
        @matrimonio.boda_civil = !params[:matrimonio][:boda_civil].blank?
        @matrimonio.boda_eclesiastica = !params[:matrimonio][:boda_eclesiastica].blank?
        @matrimonio.observacion = params[:matrimonio][:observacion]

        @el = @matrimonio.esposo
        @el.attributes = el_params
        @el.bautizado = !params[:el][:bautizado].blank?
        @el.epp = !params[:el][:epp].blank?
        @el.edl = !params[:el][:edl].blank?
        @el.seguimiento = !params[:el][:seguimiento].blank?

        @ella = @matrimonio.esposa
        @ella.attributes = ella_params
        @ella.bautizado = !params[:ella][:bautizado].blank?
        @ella.epp = !params[:ella][:epp].blank?
        @ella.edl = !params[:ella][:edl].blank?
        @ella.seguimiento = !params[:ella][:seguimiento].blank?

        raise Util::Mensaje.mensajes_error_modelo(@matrimonio.errors) unless @matrimonio.save
        raise Util::Mensaje.mensajes_error_modelo(@el.errors) unless @el.save
        raise Util::Mensaje.mensajes_error_modelo(@ella.errors) unless @ella.save

        flash[:notice] = 'Actualizado correctamente'
      end
    rescue StandardError => e
      flash[:alert] = 'Error al actualizar: ' + Util::Mensaje.limpiar_mensaje(e.message)
    ensure
      redirect_to '/matrimonios/' + @matrimonio.id.to_s + '/edit'
    end
  end

  # DELETE /matrimonios/1
  # DELETE /matrimonios/1.json
  def destroy
    begin
      result = true
      mensaje = 'Eliminado correctamente'
      raise Util::Mensaje.mensajes_error_modelo(@matrimonio.errors) unless @matrimonio.destroy
    rescue StandardError => e
      result = false
      mensaje = 'Error al eliminar: ' + Util::Mensaje.limpiar_mensaje(e.message)
    ensure
      render json: { result: result, mensaje: mensaje }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_matrimonio
    @matrimonio = Matrimonio.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def matrimonio_params
    params.require(:matrimonio).permit(:esposo_id,
                                       :esposa_id,
                                       :boda_civil,
                                       :boda_eclesiastica,
                                       :observacion)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def el_params
    params.require(:el).permit(:primer_nombre,
                               :segundo_nombre,
                               :primer_apellido,
                               :segundo_apellido,
                               :telefono,
                               :sexo,
                               :celular,
                               :email,
                               :bautizado,
                               :epp,
                               :edl,
                               :observacion,
                               :direccion)
  end

  def ella_params
    params.require(:ella).permit(:primer_nombre,
                                 :segundo_nombre,
                                 :primer_apellido,
                                 :segundo_apellido,
                                 :telefono,
                                 :sexo,
                                 :celular,
                                 :email,
                                 :bautizado,
                                 :epp,
                                 :edl,
                                 :observacion,
                                 :direccion)
  end
end

app/helpers/matrimonios_helper.rb
module MatrimoniosHelper
end

app/views/matrimonios/_resumen.html.erb
<div class="row">
  <div class="form-group">
    <%= label_tag 'esposo', 'Esposo', class: 'col-sm-1 control-label' %>
    <div class="col-sm-11">
      <%= @matrimonio.esposo.nombre_completo %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group">
    <%= label_tag 'esposa', 'Esposa', class: 'col-sm-1 control-label' %>
    <div class="col-sm-11">
      <%= @matrimonio.esposa.nombre_completo %>
    </div>
  </div>
</div>

app/views/matrimonios/edit.html.erb
<section class="content-header">
  <h1>
    <span class="text-<%= case @matrimonio.estado_civil
                               when 0
                                'danger'
                               when 1
                                'warning'
                               when 2
                                'primary'
                                end %>">
    <%= @matrimonio.situacion %></span>
    <small>Editar #<%=@matrimonio.id%></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="/matrimonios"><i class="fa fa-book"></i> Matriminios</a></li>
    <li class="active">Editar</li>
  </ol>
</section>

<section class="content">
  <div class="box">

    <%= form_tag(('/matrimonios/'+@matrimonio.id.to_s), method: 'put', class: 'form-horizontal') do -%>

    <div class="box-header with-border">
      <div class="row">
        <div class="col-xs-12 col-md-9">
          <h5><strong>
          <span class="text-<%= case @matrimonio.estado_civil
                               when 0
                                'danger'
                               when 1
                                'warning'
                               when 2
                                'primary'
                                end %>"><%= @matrimonio.situacion %></span>
          <%= @matrimonio.nombre %>
          </strong>
        </h5>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= link_to 'Regresar', @matrimonio , class: "btn btn-default btn-block"%>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= submit_tag 'Guardar', class: "btn btn-primary btn-block" %>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= link_to 'Nuevo', new_matrimonio_path, { class: 'btn btn-primary btn-block'} %>
        </div>
      </div>
    </div>
    <div class="box-body">
      <%= render 'form', matrimonio: @matrimonio %>
    </div>
  </div>
  <% end -%>
</section>

app/views/matrimonios/index.html.erb
<%= render 'shared/page_title', title: 'Matrimonios',
                                small_title: 'lista',
                                navigation: [{ title: 'Matrimonios', url: '/matrimonios', icon: 'fa-book' }] %>
<section class="content">
  <div class="box box-primary">
    <div class="box-header">
        <div class="row">
          <div class="col-xs-12 col-md-10">
            <div class="input-group input-group-xs" >
              <input id="txt-buscar" class="form-control pull-right" placeholder="Buscar..." type="text">
              <div class="input-group-btn">
                <button id="btn-buscar" class="btn btn-default">
                  <i class="fa fa-search"></i>
                </button>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-md-2">
            <% if can? :create, Matrimonio %>
            <%= link_to 'Nuevo', new_matrimonio_path, { class: 'btn btn-primary btn-block'} %>
            <% end %>
          </div>
        </div>
    </div>
    <div class="box-body">
      <div id="registros"></div>
    </div>
  </div>
</section>
<script>
  function buscar_matrimonios(buscar){
    $.get('/matrimonios/lista', { buscar: buscar },
      function(data){
        $('#registros').empty();
        $('#registros').append(data);
      }
    );
  }

  $("#btn-buscar").click(function(){
    buscar_matrimonios($('#txt-buscar').val());
  });

  $("#txt-buscar").keypress(function(e) {
    var keycode = (e.keyCode ? e.keyCode : e.which);
    if (keycode == '13') {
        buscar_matrimonios($('#txt-buscar').val());
    }
  });

  function fn_eliminar(id){

(new PNotify({
    title: 'Confirmación',
    text: 'Seguro de eliminar?',
    icon: 'glyphicon glyphicon-question-sign',
    hide: false,
    confirm: {
        confirm: true
    },
    buttons: {
        sticker: false
    },
    history: {
        history: false
    },
    stack: {
        'dir1': 'down',
        'dir2': 'right',
        'modal': true
    }
  })).get().on('pnotify.confirm', function() {
      $.post('/matrimonios/destroy', {id: id}, function(data){
      if(data.result = true){
        $('#fila-' + id).remove();
        mostrarMensaje('Éxito', data.mensaje, 'success');
      }else {
        mostrarMensaje('Error', data.mensaje, 'error');
      }
    });
});


  }

  <% unless @buscar.blank? %>
  $(document).ready(function() {
    $("#txt-buscar").val('<%= @buscar %>');
    buscar_matrimonios('<%= @buscar %>');
  });
  <% end %>

</script>

app/views/matrimonios/matrimonios.html.erb
<% @matrimonios.each_with_index do |m, index| %>


<%
next unless current_usuario.es_matrimonio_asignado?(m) || current_usuario.es_admin? || current_usuario.es_coordinador?
%>

<div id="fila-<%= m.id %>" class="row row-coustom <%= 'row-coustom-background' if index.even? %>" >

  <div class="col-xs-12 col-md-3">
      <a href="/matrimonios/<%= m.id %>"><%= m.situacion_nombre %></a>
  </div>

  <div class="col-xs-12 col-md-7  ">
      <ul class="list-unstyled">
        <li>
          <%= m.esposo.nombre_completo %> <%= '|' unless m.esposo.telefono.blank? %> <%= m.esposo.telefono %></li>
        <li><%= m.esposa.nombre_completo %> <%= '|' unless m.esposa.telefono.blank? %> <%= m.esposa.telefono %></li>
      </ul>
  </div>

  <div class="col-xs-6 col-md-1">
    <span data-toggle="tooltip" data-placement="bottom" title="Actividades asistidas" ><%= m.actividades.count %></span>
    |
    <span data-toggle="tooltip" data-placement="bottom" title="Fecha última actividad" ><%= m.actividades.last.try(:actividad).try(:fecha) %></span>
  </div>


  <div class="col-xs-1 col-md-1">
    <% if can? :destroy, m %>
      <% unless m.tiene_actividades? %>
      <button class="btn btn-danger" onclick="fn_eliminar(<%= m.id %>);">
        <i class="fa fa-trash" style="color: #ffffff"></i>
      </button>
      <% else %>
      <button class="btn btn-default" disabled="disabled" data-placement="bottom" title="No se puede eliminar porque notas de seguimiento o actividades">
        <i class="fa fa-trash-o" style="color: #777777"></i>
      </button>
      <% end %>
    <% end %>
  </div>

</div>
<% end %>
<script type="text/javascript">
$(function () {
  $('[data-toggle="tooltip"]').tooltip();
});
</script>

app/views/matrimonios/new.html.erb
<section class="content-header">
  <h1>
    Matrimonio
    <small>Nuevo</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="/matrimonios"><i class="fa fa-book"></i> Matriminios</a></li>
    <li class="active">Nuevo</li>
  </ol>
</section>

<section class="content">
  <div class="box">
    <%= form_tag('/matrimonios', class: 'form-horizontal') do -%>
    <div class="box-header with-border">
      <div class="row">
        <div class="col-xs-12 col-md-10"></div>
        <div class="col-xs-6 col-md-1">
          <%= link_to 'Regresar', matrimonios_path, {class: 'btn btn-default btn-block'} %>
        </div>
        <div class="col-xs-6 col-md-1">
          <%= submit_tag 'Guardar', class: "btn btn-primary btn-block" %>
        </div>
      </div>
    </div>

    <div class="box-body">
      <%= render 'form', matrimonio: @matrimonio %>
    </div>
  <% end -%>
</section>

app/views/matrimonios/show.html.erb
<section class="content-header">
  <h1>
    <span class="text-<%= case @matrimonio.estado_civil
                               when 0
                                'danger'
                               when 1
                                'warning'
                               when 2
                                'primary'
                                end %>">
    <%= @matrimonio.situacion %></span>
    <small>ID #<%=@matrimonio.id%></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="/matrimonios"><i class="fa fa-circle-o"></i> Matriminios</a></li>
    <li class="active">Ver</li>
  </ol>
</section>

<section class="content">

  <!-- Datos personales -->
  <div class="box box-primary">

    <div class="box-header with-border">
      <h3 class="box-title">
        <span class="text-<%= case @matrimonio.estado_civil
                               when 0
                                'danger'
                               when 1
                                'warning'
                               when 2
                                'primary'
                                end %>"><%= @matrimonio.situacion %></span>
        <%= @matrimonio.nombre %>
      </h3>
      <div class="box-tools pull-right">
        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
      </div>
    </div>

    <div class="box-body">
        <div class="row">
          <div class="col-xs-12 col-md-10"></div>
          <div class="col-xs-6 col-md-1">
            <%= link_to 'Regresar', matrimonios_path , class: "btn btn-default btn-block"%>
          </div>
          <div class="col-xs-6 col-md-1">
            <% if can? :update, @matrimonio %>
            <%= link_to 'Editar', edit_matrimonio_path(@matrimonio), class: "btn btn-primary btn-block" %>
            <% end -%>
          </div>
      </div>
      <br>
      <div id="datos_personales">



<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="box">
        <div class="box-body">
          <div class="row">
            <div class="col-xs-6 col-md-2">
              <div class="form-group">
              <%= label_tag 'matrimonio_boda_civil', 'Boda Civil', class: 'col-sm-10 control-label' %>
              <div class="col-sm-2">
                <%= check_box_tag 'matrimonio[boda_civil]',1 ,@matrimonio.boda_civil %>
              </div>
            </div>
            </div>
            <div class="col-xs-6 col-md-2">
              <div class="form-group">
              <%= label_tag 'matrimonio_boda_eclesiastica', 'Boda Eclesiástica', class: 'col-sm-10 control-label' %>
              <div class="col-sm-2">
                <%= check_box_tag 'matrimonio[boda_eclesiastica]',1 ,@matrimonio.boda_eclesiastica %>
              </div>
            </div>
            </div>
            <div class="col-xs-12 col-md-2">

            </div>
            <div class="col-xs-12 col-md-6">
               <div class="form-group">
                <%= label_tag 'matrimonio_observacion', 'Observación', class: 'col-sm-2 control-label' %>
                <div class="col-sm-10">
                  <%= text_field_tag 'matrimonio[observacion]', @matrimonio.observacion, class: 'form-control' %>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-md-6">

    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Él</h3>
      </div>
      <div class="box-body">
        <%= render 'personas/show', persona: @matrimonio.esposo %>
      </div>
    </div>

  </div>
  <div class="col-xs-12 col-md-6">

    <div class="box box-danger">
      <div class="box-header with-border">
        <h3 class="box-title">Ella</h3>
      </div>
      <div class="box-body">
        <%= render 'personas/show', persona: @matrimonio.esposa %>
      </div>
    </div>
  </div>
</div>




      </div>
    </div>
  </div>
  <!-- /Datos personales -->

  <!-- Actividades -->
  <div class="box box-primary">

  <div class="box-header with-border">
    <h3 class="box-title">Actividades a las que ha asistido</h3>
    <div class="box-tools pull-right">
      <span data-toggle="tooltip" title="3 New Messages" class="badge bg-blue"><%= @actividades.length %></span>
      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
    </div>
  </div>

    <div class="box-body">

<ul class="timeline">
  <% @actividades.each do |actividad| %>
    <!-- timeline time label -->
    <li class="time-label">
        <span class="bg-blue">
          <%= actividad.fecha %>
        </span>
    </li>
    <!-- /.timeline-label -->

    <!-- timeline item -->
    <li>
        <!-- timeline icon -->
        <i class="fa fa-calendar bg-blue"></i>
        <div class="timeline-item">
            <span class="time"><i class="fa fa-clock-o"></i></span>
            <h3 class="timeline-header">
              <span class="text-success"><%= I18n.t("enum.actividad.tipo.#{actividad.tipo}") %></span>
              <%= actividad.nombre %>
              <span class="badge bg-blue"><%= actividad.cantidad_integrantes %></span>
            </h3>

            <div class="timeline-body">
              <%= actividad.objetivo %>
            </div>

        </div>
    </li>
  <% end %>

</ul>

    </div>
  </div>
  <!-- /Actividades -->
</section>