config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  root to: 'home#index'

  namespace :home do
    get 'lista'
  end

  namespace :usuarios do
    get 'asignaciones_seguimiento'
    post 'actualizar_clave'
    post 'agregar_seguimiento'
    post 'quitar_seguimiento'
  end

  namespace :matrimonios do
    get 'lista'
    post 'destroy'
  end

  namespace :actividades do
    get 'matrimonios'
    post 'agregar_quitar_participante'
  end

  namespace :personas do
    get 'lista'
    post 'destroy'
    post 'guardar_seguimiento'
    get 'obtener_nota'
  end

  resources :usuarios
  resources :parametros
  resources :matrimonios
  resources :actividades
  resources :circulo_amistades
  resources :personas do
    resources :personas_nota_seguimiento, except: [:index, :show]
  end
end

app/models/persona.rb
# encoding: utf-8

class Persona < ApplicationRecord

  include UpcaseAttributes
  include PgSearch

  audited
  strip_attributes

  # ------------------------------------------------------------------------------------------------
  # Validaciones
  # ------------------------------------------------------------------------------------------------

  validates :primer_nombre, presence: true,
                            length: { maximum: 20 },
                            format: { with: /\A[a-zA-Z\sáéíóúAÉÍÓÚÑñ]{0,100}\z/ }

  validates :segundo_nombre, length: { maximum: 20,
                                       allow_blank: true },
                             format: { with: /\A[a-zA-Z\sáéíóúAÉÍÓÚÑñ]{0,100}\z/,
                                       allow_blank: true }

  validates :primer_apellido, presence: true,
                              length: { maximum: 20 },
                              format: { with: /\A[a-zA-Z\sáéíóúAÉÍÓÚÑñ]{0,100}\z/ }

  validates :segundo_apellido, length: { maximum: 20,
                                         allow_blank: true },
                               format: { with: /\A[a-zA-Z\sáéíóúAÉÍÓÚÑñ]{0,100}\z/,
                                         allow_blank: true }

  validates :sexo, presence: true,
                   length: { maximum: 1 },
                   inclusion: { in: %w(F M) }

  validates :direccion, length: { maximum: 10_000,
                                  allow_blank: true }

  validates :observacion, length: { maximum: 10_000,
                                    allow_blank: true }

  validates :celular, length: { maximum: 10 },
                      format: { with: /\A[0-9]{0,10}\z/ }

  validates :telefono, length: { maximum: 10 },
                       format: { with: /\A[0-9]{0,10}\z/ }

  validates :email, length: { maximum: 30,
                              allow_blank: true },
                    format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/i,
                              allow_blank: true }

  # ------------------------------------------------------------------------------------------------
  # Relaciones
  # ------------------------------------------------------------------------------------------------

  has_one :integrante_actividades

  has_one :asignado_a,
          class_name: 'AsignacionSeguimiento',
          foreign_key: 'persona_id'

  has_one :matrimonio_esposo,
          class_name: 'Matrimonio',
          foreign_key: 'esposo_id',
          inverse_of: :esposo

  has_one :matrimonio_esposa,
          class_name: 'Matrimonio',
          foreign_key: 'esposa_id',
          inverse_of: :esposa

  has_one :usuario,
          class_name: 'Usuario',
          foreign_key: 'persona_id'

  has_many :notas_seguimiento,
           class_name: 'PersonaNotaSeguimiento',
           foreign_key: 'persona_id'

  # ------------------------------------------------------------------------------------------------
  # Callbacks
  # ------------------------------------------------------------------------------------------------
  before_destroy :relaciones?

  # ------------------------------------------------------------------------------------------------
  # Métodos
  # ------------------------------------------------------------------------------------------------

  def relaciones?
    errors.add(:base, 'Está relacionado a un matrimonio') unless matrimonio_esposo.nil?
    errors.add(:base, 'Está relacionado a un matrimonio') unless matrimonio_esposa.nil?
    errors.add(:base, 'Tiene notas de seguimiento') if notas_seguimiento.any?
    throw :abort if errors.any?
  end

  def nombre_completo
    [primer_nombre,
     segundo_nombre,
     primer_apellido,
     segundo_apellido].reject(&:blank?).join(' ')
  end

  pg_search_scope(:por_nombre,
                  against: [:primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido],
                  using: {
                    tsearch: {
                      dictionary: 'spanish',
                      normalization: 2
                    }
                  })

  def usuario_seguimiento
    asignado_a.first
  end

  def tiene_notas_seguimiento?
    notas_seguimiento.any?
  end

  def esta_asignado_al_usuario?(usuario)
    AsignacionSeguimiento.where(persona_id: id, usuario_id: usuario.id).any?
  end

  def tiene_matrimonio?
    matrimonio_esposo.present? || matrimonio_esposa.present?
  end

  def obtener_matrimonio
    try(:matrimonio_esposo) || try(:matrimonio_esposa)
  end

  def con_nota_seguimiento_dentro_del_periodo(usuario)
    @dias_atras = Parametro.find_by(codigo: '001')
    notas_seguimiento.where(personas_nota_seguimiento: { usuario_id: usuario.id })
                             .where('fecha >= ?', Date.today - @dias_atras.valor.to_i.day).any?
  end

end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]
  check_authorization
  load_and_authorize_resource

  # GET /personas
  # GET /personas.json
  def index
  end

  def lista
    @personas = []
    @personas = Persona.por_nombre(params[:buscar]) unless params[:buscar].blank?
    render 'personas', layout: false
  end

  def guardar_seguimiento
    begin
      id = 0
      result = true
      mensaje = 'Guardado correctamente'
      nota = PersonaNotaSeguimiento.new
      nota.fecha = Date.today
      nota.usuario_id = current_usuario.id
      nota.persona_id = params[:persona_id]
      nota.notas = params[:nota]
      raise Util::Mensaje.mensajes_error_modelo(nota.errors) unless nota.save
      id = nota.id
    rescue StandardError => e
      result = false
      mensaje = 'Error al eliminar: ' + Util::Mensaje.limpiar_mensaje(e.message)
    ensure
      render json: { result: result, mensaje: mensaje, id: id }
    end
  end

  def obtener_nota
    @nota = PersonaNotaSeguimiento.find(params[:id])
    render 'nota', layout: false
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona creada correctamente.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    begin
      result = true
      mensaje = 'Eliminado correctamente'
      raise Util::Mensaje.mensajes_error_modelo(@persona.errors) unless @persona.destroy
    rescue StandardError => e
      result = false
      mensaje = 'Error al eliminar: ' + Util::Mensaje.limpiar_mensaje(e.message)
    ensure
      render json: { result: result, mensaje: mensaje, id: params[:id] }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :sexo, :fecha_nacimiento, :direccion, :bautizado, :epp, :edl, :observacion, :telefono, :celular, :email, :seguimiento)
    end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
  <%= render 'shared/errors', obj: @persona %>

  <div class="form-group">
    <%= form.label :primer_nombre , '* Primer Nombre:', class: 'col-sm-2 control-label'%>
    <div class="col-sm-6">
    <%= form.text_field :primer_nombre, id: :persona_primer_nombre , class: 'form-control', required: ''%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :segundo_nombre, 'Segundo Nombre:' , class: 'col-sm-2 control-label'%>
    <div class="col-sm-6">
    <%= form.text_field :segundo_nombre, id: :persona_segundo_nombre, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :primer_apellido, '* Primer Apellido:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
    <%= form.text_field :primer_apellido, id: :persona_primer_apellido, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :segundo_apellido, 'Segundo Apellido:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
    <%= form.text_field :segundo_apellido, id: :persona_segundo_apellido, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :sexo, '* Sexo:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
    <%= form.select(:sexo, [{id:'M', name: 'MASCULINO'},{id:'F', name: 'FEMENIMO'}].map {|c| [c[:name],c[:id]]},{include_blank: true},{class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :fecha_nacimiento, 'Fecha de nacimiento:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
    <%= form.text_field :fecha_nacimiento, id: :persona_fecha_nacimiento, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :telefono, 'Teléfono:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
    <%= form.text_field :telefono, id: :persona_telefono, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :email, 'Email:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
    <%= form.text_field :email, id: :persona_email, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :direccion, 'Dirección:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
    <%= form.text_area :direccion, id: :persona_direccion, class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :bautizado, 'Bautizado:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-1">
    <%= form.check_box :bautizado, id: :persona_bautizado %>
    </div>
    <%= form.label :epp, 'EPP:', class: 'col-sm-1 control-label' %>
    <div class="col-sm-1">
    <%= form.check_box :epp, id: :persona_epp %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :edl, 'EDL:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-1">
    <%= form.check_box :edl, id: :persona_edl %>
    </div>
    <%= form.label :seguimiento, 'Seguimiento:', class: 'col-sm-1 control-label' %>
    <div class="col-sm-1">
    <%= form.check_box :seguimiento, id: :persona_seguimiento %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :observacion, 'Observación:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
    <%= form.text_area :observacion, id: :persona_observacion, class: 'form-control' %>
    </div>
  </div>
<script>
  $(document).ready(function() {
    $('#persona_fecha_nacimiento').daterangepicker({
      "singleDatePicker": true,
      "showDropdowns": true,
      "autoApply": true,
      "autoUpdateInput": false,
      "locale": {
                  format: 'YYYY-MM-DD'
                },
    });
  });
</script>

app/views/personas/_resumen.html.erb
    <div class="row">
      <div class="col-xs-3">
        <strong>Nombres:</strong>
      </div>
      <div class="col-xs-9">
        <%= persona.primer_nombre %> <%= persona.segundo_nombre %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Apellidos:</strong>
      </div>
      <div class="col-xs-9">
        <%= persona.primer_apellido %> <%= persona.segundo_apellido %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Sexo:</strong>
      </div>
      <div class="col-xs-9">
        <%= persona.sexo %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Fecha nacimiento:</strong>
      </div>
      <div class="col-xs-9">
        <%= persona.fecha_nacimiento %>
      </div>
    </div>

app/views/personas/_show.html.erb
    <div class="row">
      <div class="col-xs-3">
        <strong>Nombres:</strong>
      </div>
      <div class="col-xs-9">
        <%= persona.primer_nombre %> <%= persona.segundo_nombre %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Apellidos:</strong>
      </div>
      <div class="col-xs-9">
        <%= persona.primer_apellido %> <%= persona.segundo_apellido %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Sexo:</strong>
      </div>
      <div class="col-xs-9">
        <%= persona.sexo %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Fecha nacimiento:</strong>
      </div>
      <div class="col-xs-9">
        <%= persona.fecha_nacimiento %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Teléfono:</strong>
      </div>
      <div class="col-xs-9">
        <%= persona.telefono %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Email:</strong>
      </div>
      <div class="col-xs-9">
        <%= persona.email %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Dirección:</strong>
      </div>
      <div class="col-xs-9">
        <%= simple_format(persona.direccion) %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Bautizado:</strong>
      </div>
      <div class="col-xs-3">
        <%= I18n.t("boolean.#{persona.bautizado}") %>
      </div>
      <div class="col-xs-3">
        <strong>EPP:</strong>
      </div>
      <div class="col-xs-3">
        <%= I18n.t("boolean.#{persona.epp}") %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>EDL:</strong>
      </div>
      <div class="col-xs-3">
        <%= I18n.t("boolean.#{persona.edl}") %>
      </div>
      <div class="col-xs-3">
        <strong>Seguimiento:</strong>
      </div>
      <div class="col-xs-3">
        <%= I18n.t("boolean.#{persona.seguimiento}") %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
        <strong>Observación:</strong>
      </div>
      <div class="col-xs-9">
        <%= simple_format(persona.observacion) %>
      </div>
    </div>
  </br>
    <div class="box box-primary direct-chat direct-chat-primary"">

    <div class="box-header with-border">
      <div class="row">
        <div class="col-xs-6 col-md-10">
          <h3 class="box-title">
            Seguimiento
          </h3>
        </div>
        <div class="col-xs-6 col-md-2">
          <div class="pull-right">
          <% if persona.seguimiento %>
          <%= link_to 'Nuevo', new_persona_persona_nota_seguimiento_path(persona.id), { class: 'btn btn-primary btn-block'} %>
          <% end %>
          </div>
        </div>
      </div>
    </div>

      <div class="box-body">
        <a id="esposo_seguimiento"></a>
        <div id="notas_seguimiento_el" class="direct-chat-messages" style="height: auto; max-height: 450px;">
          <%= render persona.notas_seguimiento.order(fecha: :desc) %>
        </div>
      </div>
    </div>

app/views/personas/edit.html.erb
<%= render 'shared/page_title', title: 'Persona',
                                small_title: "ID ##{@persona.id}",
                                navigation: [{ title: 'Personas', url: '/personas', icon: 'fa-user' },
                                             { title: 'Editar', url: '#', icon: 'fa-circle-o' }] %>
<section class="content">
  <div class="box box-primary">
  <%= form_with(model: @persona, local: true, class: 'form-horizontal') do |form| %>
    <div class="box-header with-border">
      <div class="row">
        <div class="col-xs-12 col-md-9">
        </div>
        <div class="col-xs-4 col-md-1">
          <%= submit_tag 'Guardar', class: "btn btn-primary btn-block" %>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= link_to 'Nuevo', new_persona_path, { class: 'btn btn-primary btn-block'} %>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= link_to 'Regresar', personas_path, class: 'btn btn-default btn-block' %>
        </div>
      </div>
    </div>
    <div class="box-body">
    <%= render 'form', persona: @persona, form: form %>
    </div>
  <% end %>
  </div>
</section>

app/views/personas/index.html.erb
<%= render 'shared/page_title', title: 'Personas',
                                small_title: 'lista',
                                navigation: [{ title: 'Personas', url: '/personas', icon: 'fa-user' }] %>
<section class="content">
  <div class="box box-primary">
    <div class="box-header">
        <div class="row">
          <div class="col-xs-12 col-md-10">
            <div class="input-group input-group-xs" >
              <input id="txt-buscar" class="form-control pull-right" placeholder="Buscar..." type="text">
              <div class="input-group-btn">
                <button id="btn-buscar" class="btn btn-default">
                  <i class="fa fa-search"></i>
                </button>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-md-2">
            <%= link_to 'Nuevo', new_persona_path, { class: 'btn btn-primary btn-block'} %>
          </div>
        </div>
    </div>
    <div class="box-body">
      <div id="registros"></div>
    </div>
  </div>
</section>
<script>
  function buscar_persona(buscar){
    $.get('/personas/lista', { buscar: buscar },
      function(data){
        $('#registros').empty();
        $('#registros').append(data);
      }
    );
  }

  $("#btn-buscar").click(function(){
    buscar_persona($('#txt-buscar').val());
  });

  $("#txt-buscar").keypress(function(e) {
    var keycode = (e.keyCode ? e.keyCode : e.which);
    if (keycode == '13') {
        buscar_persona($('#txt-buscar').val());
    }
  });


  function fn_eliminar(persona_id){
    (new PNotify({
        title: 'Confirmación',
        text: 'Seguro de eliminar?',
        icon: 'glyphicon glyphicon-question-sign',
        hide: false,
        confirm: {
            confirm: true
        },
        buttons: {
            sticker: false
        },
        history: {
            history: false
        },
        stack: {
            'dir1': 'down',
            'dir2': 'right',
            'modal': true
        }
      })).get().on('pnotify.confirm', function() {

        $.ajax({
              url:   "/personas/"+persona_id,
              type:  'delete',
              success:  function (data) {
                if(data.result == true){
                  $('#fila-' + data.id).remove();
                  mostrarMensaje('Éxito', data.mensaje, 'success');
                }else {
                  mostrarMensaje('Error', data.mensaje, 'error');
                }
              }
          });
    });
  }



</script>

app/views/personas/new.html.erb
<%= render 'shared/page_title', title: 'Persona',
                                small_title: 'Nueva',
                                navigation: [{ title: 'Personas', url: '/personas', icon: 'fa-user' },
                                             { title: 'Nueva', url: '#', icon: 'fa-circle-o' }] %>
<section class="content">
  <div class="box box-primary">
  <%= form_with(model: @persona, local: true, class: 'form-horizontal') do |form| %>
    <div class="box-header with-border">
      <div class="row">
        <div class="col-xs-12 col-md-9">
        </div>
        <div class="col-xs-4 col-md-1">
        </div>
        <div class="col-xs-4 col-md-1">
          <%= submit_tag 'Guardar', class: "btn btn-primary btn-block" %>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= link_to 'Regresar', personas_path, class: 'btn btn-default btn-block' %>
        </div>
      </div>
    </div>
    <div class="box-body">
    <%= render 'form', persona: @persona, form: form %>
    </div>
  <% end %>
  </div>
</section>

app/views/personas/personas.hmtl.erb
<% @personas.each_with_index do |p, index| %>


<%
next unless current_usuario.es_persona_asignada?(p) || current_usuario.es_admin? || current_usuario.es_coordinador?
%>

<div id="fila-<%= p.id %>" class="row row-coustom <%= 'row-coustom-background' if index.even? %>" >

  <div class="col-xs-12 col-md-3">
      <a href="/personas/<%= m.id %>"><%= p.nombre_completo %> <%= '|' unless p.telefono.blank? %> <%= p.telefono %></a>
  </div>

  <div class="col-xs-1 col-md-1">
    <button class="btn btn-danger" onclick="fn_eliminar(<%= m.id %>);">
      <i class="fa fa-trash" style="color: #ffffff"></i>
    </button>
  </div>

</div>
<% end %>
<script type="text/javascript">
$(function () {
  $('[data-toggle="tooltip"]').tooltip();
});
</script>

app/views/personas/personas.html.erb
<% @personas.each_with_index do |p, index| %>
<%
next unless current_usuario.es_persona_asignada?(p) || current_usuario.es_admin? || current_usuario.es_coordinador?
%>

<div id="fila-<%= p.id %>" class="row row-coustom <%= 'row-coustom-background' if index.even? %>" >

  <div class="col-xs-1 col-md-1">
    <strong>
      <%= index + 1 %>
    </strong>
  </div>

  <div class="col-xs-12 col-md-10">
      <a href="/personas/<%= p.id %>"><%= p.nombre_completo %> <%= '|' unless p.telefono.blank? %> <%= p.telefono %></a>
  </div>

  <div class="col-xs-1 col-md-1">
    <button class="btn btn-danger" onclick="fn_eliminar(<%= p.id %>);">
      <i class="fa fa-trash" style="color: #ffffff"></i>
    </button>
  </div>

</div>
<% end %>

app/views/personas/show.html.erb
<%= render 'shared/page_title', title: 'Persona',
                                small_title: "ID ##{@persona.id}",
                                navigation: [{ title: 'Personas', url: '/personas', icon: 'fa-user' },
                                             { title: 'Ver', url: '#', icon: 'fa-circle-o' }] %>
<section class="content">
  <div class="box box-primary">

    <div class="box-header with-border">
      <div class="row">
        <div class="col-xs-12 col-md-9">
          <h3 class="box-title">
            <%= @persona.nombre_completo %>
          </h3>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= link_to 'Nuevo', new_persona_path, { class: 'btn btn-primary btn-block'} %>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= link_to 'Editar',edit_persona_path(@persona), class: "btn btn-primary btn-block" %>
        </div>
        <div class="col-xs-4 col-md-1">
          <%= link_to 'Regresar', personas_path, class: 'btn btn-default btn-block' %>
        </div>
      </div>
    </div>

    <div class="box-body">
      <%= render 'show', persona: @persona %>
    </div>
  </div>
</section>