config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  root to: 'home#index'

  namespace :home do
    get 'lista'
  end

  namespace :usuarios do
    get 'asignaciones_seguimiento'
    post 'actualizar_clave'
    post 'agregar_seguimiento'
    post 'quitar_seguimiento'
  end

  namespace :matrimonios do
    get 'lista'
    post 'destroy'
  end

  namespace :actividades do
    get 'matrimonios'
    post 'agregar_quitar_participante'
  end

  namespace :personas do
    get 'lista'
    post 'destroy'
    post 'guardar_seguimiento'
    get 'obtener_nota'
  end

  resources :usuarios
  resources :parametros
  resources :matrimonios
  resources :actividades
  resources :circulo_amistades
  resources :personas do
    resources :personas_nota_seguimiento, except: [:index, :show]
  end
end

app/controllers/actividades_controller.rb
# encoding: utf-8

class ActividadesController < ApplicationController
  before_action :set_actividad, only: [:show, :edit, :update, :destroy]
  check_authorization
  load_and_authorize_resource

  # GET /actividades
  # GET /actividades.json
  def index
    @buscar = params[:buscar]
    @tipo = params[:tipo]
    @actividades = @buscar.blank? ? Actividad.order('fecha desc') : Actividad.buscar(@buscar)
    @actividades = @actividades.where(tipo: @tipo.to_i) unless @tipo.blank?
  end

  def matrimonios
    @actividad = Actividad.find(params[:actividad_id])
    @matrimonios = if params[:buscar].blank?
                     Matrimonio.joins(:actividades).where( integrante_actividades: { actividad_id: @actividad.id})
                   else
                     Matrimonio.buscar(params[:buscar])
                   end

    render 'matrimonios', layout: false
  end

  def agregar_quitar_participante
    result = true
    mensaje = ''
    begin
      actividad = Actividad.find(params[:actividad_id])
      integrante = IntegranteActividad.where(actividad_id: params[:actividad_id],
                                             matrimonio_id: params[:matrimonio_id]).first
      if integrante.nil?
        integrante = IntegranteActividad.new
        integrante.actividad_id = params[:actividad_id]
        integrante.matrimonio_id = params[:matrimonio_id]
        raise Util::Mensaje.mensajes_error_modelo(integrante.errors) unless integrante.save
        mensaje = 'Agregardo Correctamente'
      else
        raise Util::Mensaje.mensajes_error_modelo(integrante.errors) unless integrante.destroy
        mensaje = 'Eliminado Correctamente'
      end
    rescue StandardError => e
      result = false
      mensaje = Util::Mensaje.limpiar_mensaje(e.message)
    ensure
      render json: { result: result,
                     mensaje: mensaje,
                     cantidad_integrantes: actividad.cantidad_integrantes }
    end
  end

  # GET /actividades/1
  # GET /actividades/1.json
  def show
  end

  # GET /actividades/new
  def new
    @actividad = Actividad.new
  end

  # GET /actividades/1/edit
  def edit
  end

  # POST /actividades
  # POST /actividades.json
  def create
    @actividad = Actividad.new(actividad_params)

    respond_to do |format|
      if @actividad.save
        format.html { redirect_to @actividad, notice: 'Creado correctamente.' }
        format.json { render :show, status: :created, location: @actividad }
      else
        format.html { render :new }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actividades/1
  # PATCH/PUT /actividades/1.json
  def update
    respond_to do |format|
      if @actividad.update(actividad_params)
        format.html { redirect_to @actividad, notice: 'Actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @actividad }
      else
        format.html { render :edit }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actividades/1
  # DELETE /actividades/1.json
  def destroy
    @actividad.destroy
    respond_to do |format|
      format.html { redirect_to actividades_url, notice: 'Borrado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actividad
      @actividad = Actividad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actividad_params
      params.require(:actividad).permit(:nombre, :fecha, :objetivo, :reporte, :tipo, :observacion)
    end
end

app/helpers/actividades_helper.rb
module ActividadesHelper
end

app/views/actividades/_form.html.erb
    <div class="form-group">
      <%= form.label :tipo , '*Tipo:', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
       <%= form.select :tipo, Actividad.tipos.map{ |p| [t("enum.actividad.tipo.#{p.first}"), p.first] }, { include_blank: true }, { class: 'form-control' } %>
     </div>
   </div>

   <div class="form-group">
    <%= form.label :fecha , '*Fecha:', class: 'col-sm-2 control-label'%>
    <div class="col-sm-10">
      <%= form.text_field :fecha, id: :actividad_fecha, class: "form-control daterange"%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :nombre , '*Nombre:', class: 'col-sm-2 control-label'%>
    <div class="col-sm-10">
      <%= form.text_field :nombre, id: :actividad_nombre, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :objetivo , '*Objetivo:', class: 'col-sm-2 control-label'%>
    <div class="col-sm-10">
      <%= form.text_area :objetivo, id: :actividad_objetivo, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :observacion , 'Observación:', class: 'col-sm-2 control-label'%>
    <div class="col-sm-10">
      <%= form.text_area :observacion, id: :actividad_observacion, class: "form-control"%>
    </div>
  </div>
<script>
  $(document).ready(function() {
    $('#actividad_fecha').daterangepicker({
      "singleDatePicker": true,
      "showDropdowns": true,
      "autoApply": true,
      "locale": {
                  format: 'YYYY-MM-DD'
                },
    });
  });
</script>

app/views/actividades/edit.html.erb
<%= render 'shared/page_title', title: 'Actividad',
                                small_title: "ID ##{@actividad.id}",
                                navigation: [{ title: 'Actividades', url: '/actividades', icon: 'fa-calendar' },
                                             { title: 'Editar', url: '#', icon: 'fa-circle-o' }] %>
<section class="content">
<%= form_with(model: @actividad, local: true, class: 'form-horizontal') do |form| %>
<div class="box box-primary">

    <div class="box-header with-border">
      <div class="row">
        <div class="col-xs-12 col-md-10">
          <h5><strong>
            Datos de la actividad
          </strong>
        </h5>
        </div>
        <div class="col-xs-6 col-md-1">
          <%= link_to 'Regresar', @actividad , class: 'btn btn-default btn-block'%>
        </div>
        <div class="col-xs-6 col-md-1">
          <%= submit_tag 'Guardar', class: "btn btn-primary btn-block" %>
        </div>
      </div>
    </div>
  <div class="box-body">
    <%= render 'form', actividad: @actividad, form: form %>
  </div>
</div>
<% end %>
</section>

app/views/actividades/index.html.erb
<%= render 'shared/page_title', title: 'Actividades',
                                small_title: 'lista',
                                navigation: [{ title: 'Actividades', url: '/actividades', icon: 'fa-calendar' }] %>
<section class="content">
  <div class="box box-primary">
    <div class="box-header">
      <%= form_tag('/actividades', method: :get) do -%>
      <div class="row">

       <div class="col-xs-12 col-md-2">
        <%= select_tag :tipo,
        options_for_select(Actividad.tipos.map{ |p| [t("enum.actividad.tipo.#{p.first}"), p.last] }),
        { include_blank: true, class: 'form-control' }
        %>
      </div>

      <div class="col-xs-12 col-md-8">
        <div class="input-group input-group-xs" >
          <input id="buscar" name="buscar" class="form-control pull-right" placeholder="Buscar..." type="text">
          <div class="input-group-btn">
            <button type="submit" class="btn btn-default">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
      </div>


      <div class="col-xs-12 col-md-2">
        <% if can? :create, Actividad %>
        <%= link_to 'Nuevo', new_actividad_path, { class: 'btn btn-primary btn-block'} %>
        <% end %>
      </div>

    </div>
    <% end -%>
  </div>
  <div class="box-body">
    <% @actividades.each do |actividad| %>
    <div class="row" style="border-bottom: dotted 1px #999; padding-bottom: 5px">
      <div class="col-xs-12 col-md-1">
        <strong>
          <a href="/actividades/<%= actividad.id %>"><%= actividad.fecha %></a>
        </strong>
      </div>
      <div class="col-xs-12 col-md-10">
        <dl>
          <dt>
            <span class="text-success"><%= I18n.t("enum.actividad.tipo.#{actividad.tipo}") %></span>
            <%= actividad.nombre %>
            <span class="badge bg-blue"><%= actividad.cantidad_integrantes %></span>
          </dt>
          <dd><%= actividad.objetivo %></dd>
        </dl>
      </div>
      <div class="col-xs-12 col-md-1">
        <% unless actividad.tiene_integrantes? %>
        <%= link_to 'Borrar', actividad, class: 'btn btn-danger btn-xs btn-block', method: :delete, data: { confirm: 'Seguro de eliminar?' } %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>
</section>

<script>
  $('#buscar').val('<%= @buscar %>');
  $('#tipo').val(<%= @tipo %>);
</script>

app/views/actividades/matrimonios.html.erb
<% @matrimonios.each do |m| %>
<div class="row" style="border-bottom: dotted 1px #999; padding-bottom: 5px">
  <div class="col-xs-12 col-md-3">
    <strong>
      <a href="/matrimonios/<%= m.id %>"><%= m.nombre %></a>
    </strong>
  </div>
  <div class="col-xs-12 col-md-8">
    <strong>
    <dl>
      <dt>
        <%= m.esposo.nombre_completo %> <%= '|' unless m.esposo.telefono.blank? %> <%= m.esposo.telefono %></dt>
      <dd><%= m.esposa.nombre_completo %> <%= '|' unless m.esposa.telefono.blank? %> <%= m.esposa.telefono %></dd>
    </dl>
    </strong>
  </div>
  <div class="col-xs-12 col-md-1">
    <% if m.participa_en_actividad?(@actividad) %>
      <% if can? :destroy, IntegranteActividad %>
      <button id="btn_<%= m.id %>" onclick="agregar_quitar_participante(<%= m.id %>);" class="btn btn-danger btn-sm">Quitar</button>
      <% end %>
    <% else %>
      <% if can? :create, IntegranteActividad %>
      <button id="btn_<%= m.id %>" onclick="agregar_quitar_participante(<%= m.id %>);" class="btn btn-primary btn-sm">Agregar</button>
      <% end %>
    <% end %>
  </div>
</div>
<% end %>
<script>
  $('#cantidad_integrantes').html(<%= @actividad.cantidad_integrantes %>);
</script>

app/views/actividades/new.html.erb
<%= render 'shared/page_title', title: 'Nueva Actividad',
                                small_title: "",
                                navigation: [{ title: 'Actividades', url: '/actividades', icon: 'fa-calendar' },
                                             { title: 'Nueva', url: '#', icon: 'fa-circle-o' }] %>
<section class="content">
<%= form_with(model: @actividad, local: true, class: 'form-horizontal') do |form| %>
<div class="box box-primary">
    <div class="box-header with-border">
      <div class="row">
        <div class="col-xs-12 col-md-10">
          <h5><strong>Datos de la actividad</strong></h5>
        </div>
        <div class="col-xs-6 col-md-1">
          <%= link_to 'Regresar', @actividad , class: "btn btn-default btn-block"%>
        </div>
        <div class="col-xs-6 col-md-1">
          <%= form.submit 'Guardar', class: 'btn btn-primary btn-block' %>
        </div>
      </div>
    </div>
  <div class="box-body">
<%= render 'form', actividad: @actividad, form: form %>
</div>
</div>
<% end %>
</section>

app/views/actividades/show.html.erb
<%= render 'shared/page_title', title: 'Actividad',
                                small_title: "ID ##{@actividad.id} " + I18n.t("enum.actividad.tipo.#{@actividad.tipo}") +' ' + @actividad.nombre,
                                navigation: [{ title: 'Actividades', url: '/actividades', icon: 'fa-calendar' },
                                             { title: 'Ver', url: '#', icon: 'fa-circle-o' }] %>
<section class="content">
  <div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#tab_1" data-toggle="tab">Datos de la actividad</a></li>
      <li>
        <a href="#tab_2" data-toggle="tab">
          <span>Integrantes</span>
          <span id="cantidad_integrantes", class="badge bg-blue"></span>
        </a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="tab_1">
        <div class="box box-primary">
          <div class="box-header with-border">
            <div class="row">
              <div class="col-xs-12 col-md-10">
              </div>
              <div class="col-xs-6 col-md-1">
                <%= link_to 'Regresar', actividades_path , class: "btn btn-default btn-block"%>
              </div>
              <div class="col-xs-6 col-md-1">
                <% if can? :update, @actividad %>
                <%= link_to 'Editar', edit_actividad_path(@actividad), class: "btn btn-primary btn-block" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="box-body">
            <form action="" class="form-horizontal">
              <div class="form-group">
                <label class="col-sm-2 control-label">Tipo:</label>

                <div class="col-sm-10">
                  <input class="form-control" type="text" disabled="disabled" value="<%= I18n.t("enum.actividad.tipo.#{@actividad.tipo}") %>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label">Fecha:</label>

                <div class="col-sm-10">
                  <input class="form-control" type="text" disabled="disabled" value="<%= @actividad.fecha %>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label">Nombre:</label>

                <div class="col-sm-10">
                  <input class="form-control" type="text" disabled="disabled" value="<%= @actividad.nombre %>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label">Objetivo:</label>
                <div class="col-sm-10">
                  <textarea class="form-control" rows="2" disabled="disabled"><%= @actividad.objetivo %></textarea>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label">Observación:</label>
                <div class="col-sm-10">
                  <textarea class="form-control" rows="2" disabled="disabled"><%= @actividad.observacion %></textarea>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <!-- /.tab-pane -->
      <div class="tab-pane" id="tab_2">
        <div class="box box-primary">
          <div class="box-header">
            <div class="row">
              <div class="col-xs-12 col-md-10">
                <div class="input-group input-group-xs" >
                  <input id="txt-buscar" name="buscar" class="form-control pull-right" placeholder="Buscar..." type="text">
                  <div class="input-group-btn">
                    <button id="btn-buscar" class="btn btn-default">
                      <i class="fa fa-search"></i>
                    </button>
                  </div>
                </div>
              </div>
              <div class="col-xs-12 col-md-2">
                <% if can? :create, IntegranteActividad %>
                <%= link_to 'Nuevo', new_matrimonio_path, { target: '_blank', class: 'btn btn-primary btn-block'} %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="box-body">
            <div id="registros"></div>
          </div>
        </div>
      </div>
      <!-- /.tab-pane -->
    </div>
    <!-- /.tab-content -->
  </div>
</section>
<script type="text/javascript">

  $(document).ready(function() {
    buscar_matrimonios();
  });

  function buscar_matrimonios(buscar){
    $.get('/actividades/matrimonios', { buscar: buscar, actividad_id: <%= @actividad.id %> },
      function(data){
        $('#cantidad_integrantes').html('0');
        $('#registros').empty();
        $('#registros').append(data);
      }
    );
  }

  function agregar_quitar_participante(matrimonio_id){
    $.post('/actividades/agregar_quitar_participante', { matrimonio_id: matrimonio_id,
                                                         actividad_id: <%= @actividad.id %> },
      function(data){
        if(data.result){
          if($('#btn_'+ matrimonio_id).hasClass('btn-danger')){
            $('#btn_'+ matrimonio_id).addClass('btn-primary').removeClass('btn-danger').html('Agregar');
          }else{
            $('#btn_'+ matrimonio_id).addClass('btn-danger').removeClass('btn-primary').html('Quitar');
          }
          $('#cantidad_integrantes').html(data.cantidad_integrantes);
          mostrarMensaje('Éxito', data.mensaje, 'success');
        }else{
          mostrarMensaje('Error', data.mensaje, 'error');
        }
      }
    );
  }

  $("#btn-buscar").click(function(){
    buscar_matrimonios($('#txt-buscar').val());
  });

  $("#txt-buscar").keypress(function(e) {
    var keycode = (e.keyCode ? e.keyCode : e.which);
    if (keycode == '13') {
        buscar_matrimonios($('#txt-buscar').val());
    }
  });

</script>